package modelo.entidades;
// Generated 9 feb. 2021 10:03:18 by Hibernate Tools 5.4.21.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Libro generated by hbm2java
 */
public class Libro implements java.io.Serializable {

	private String codLibro;
	private String titulo;
	private String editorial;
	private Float precio;
	private Set autors = new HashSet(0);
	private Set ejemplars = new HashSet(0);

	public Libro() {
	}

	public Libro(String codLibro) {
		this.codLibro = codLibro;
	}

	public Libro(String codLibro, String titulo, String editorial, Float precio, Set autors, Set ejemplars) {
		this.codLibro = codLibro;
		this.titulo = titulo;
		this.editorial = editorial;
		this.precio = precio;
		this.autors = autors;
		this.ejemplars = ejemplars;
	}

	public String getCodLibro() {
		return this.codLibro;
	}

	public void setCodLibro(String codLibro) {
		this.codLibro = codLibro;
	}

	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	public String getEditorial() {
		return this.editorial;
	}

	public void setEditorial(String editorial) {
		this.editorial = editorial;
	}

	public Float getPrecio() {
		return this.precio;
	}

	public void setPrecio(Float precio) {
		this.precio = precio;
	}

	public Set getAutors() {
		return this.autors;
	}

	public void setAutors(Set autors) {
		this.autors = autors;
	}

	public Set getEjemplars() {
		return this.ejemplars;
	}

	public void setEjemplars(Set ejemplars) {
		this.ejemplars = ejemplars;
	}

}
