package modelo.entidades;
// Generated 9 feb. 2021 10:03:18 by Hibernate Tools 5.4.21.Final

import java.util.Date;

/**
 * Prestamo generated by hbm2java
 */
public class Prestamo implements java.io.Serializable {

	private int idPrestamo;
	private Ejemplar ejemplarByIdUsuario;
	private Ejemplar ejemplarByIdEjemplar;
	private Date fechaPrestamo;
	private Date fechaDevolucion;

	public Prestamo() {
	}

	public Prestamo(int idPrestamo) {
		this.idPrestamo = idPrestamo;
	}

	public Prestamo(int idPrestamo, Ejemplar ejemplarByIdUsuario, Ejemplar ejemplarByIdEjemplar, Date fechaPrestamo,
			Date fechaDevolucion) {
		this.idPrestamo = idPrestamo;
		this.ejemplarByIdUsuario = ejemplarByIdUsuario;
		this.ejemplarByIdEjemplar = ejemplarByIdEjemplar;
		this.fechaPrestamo = fechaPrestamo;
		this.fechaDevolucion = fechaDevolucion;
	}

	public int getIdPrestamo() {
		return this.idPrestamo;
	}

	public void setIdPrestamo(int idPrestamo) {
		this.idPrestamo = idPrestamo;
	}

	public Ejemplar getEjemplarByIdUsuario() {
		return this.ejemplarByIdUsuario;
	}

	public void setEjemplarByIdUsuario(Ejemplar ejemplarByIdUsuario) {
		this.ejemplarByIdUsuario = ejemplarByIdUsuario;
	}

	public Ejemplar getEjemplarByIdEjemplar() {
		return this.ejemplarByIdEjemplar;
	}

	public void setEjemplarByIdEjemplar(Ejemplar ejemplarByIdEjemplar) {
		this.ejemplarByIdEjemplar = ejemplarByIdEjemplar;
	}

	public Date getFechaPrestamo() {
		return this.fechaPrestamo;
	}

	public void setFechaPrestamo(Date fechaPrestamo) {
		this.fechaPrestamo = fechaPrestamo;
	}

	public Date getFechaDevolucion() {
		return this.fechaDevolucion;
	}

	public void setFechaDevolucion(Date fechaDevolucion) {
		this.fechaDevolucion = fechaDevolucion;
	}

}
